configuration:
  interfaces:
    interface:
      - name: ge-0/0/1
        description: "TRUNK-mxpe02"
        unit: 
         name: "0"
         family: 
            bridge:
              interface_mode: "trunk"
              vlan_id_list: "300-400"
      - name: ge-0/0/2
        unit:
          name: "0"
          family:
            bridge:
              interface_mode: "access"
              vlan_id: "300"
      - name: ge-0/0/3
        unit:
          name: "0"
          family:
            bridge:
              interface_mode: "access"
              vlan_id: "400"
      - name: em0
        unit:
          name: "0"
          family:
            inet:
              address: 
                name: "172.20.1.203/24"



























#configuration:
 # interfaces:
  #  interface:
   #   - name: ge-0/0/0
    #    mtu: "9192"
     #   unit:
      #    name: "0"
       #   family: 
        #    ethernet_switching:
         #     interface_mode: access
          #    vlan:
           #     members: vlan_xxx
                