configuration:
  protocols:
    lldp:
      interface:
        - name: all
      port_description_type: interface-alias
      port_id_subtype: interface-name
    lldp_med:
      interface:
        name: all