configuration:
  snmp:
    comunity:
      authorization: read-only
      clients:
        - name: x.x.x.x/24
        - name: 0.0.0.0/0
          restrict: null
      name: noc-uc
    interface: em0.0
    trap_group:
      - name: SNMP_TRAP
        categories:
          chassis: null
          routing: null
        targets:
          name: x.x.x.x
        version: v2
      - name: SPACE
        targets:
          name: x.x.x.x
        version: v2
    trap_options:
      source_address:
        address: "{{ inventory_hostname }}"